package f1ap

func createMessage(present uint8, procedureCode ProcedureCode) MessageUnmarshaller {
	switch present {
	case F1apPduInitiatingMessage:
		switch int64(procedureCode.Value) {
		case ProcedureCode_Reset:
			return new(Reset)
		case ProcedureCode_F1Setup:
			return new(F1SetupRequest)
		case ProcedureCode_ErrorIndication:
			return new(ErrorIndication)
		case ProcedureCode_GNBDUConfigurationUpdate:
			return new(GNBDUConfigurationUpdate)
		case ProcedureCode_GNBCUConfigurationUpdate:
			return new(GNBCUConfigurationUpdate)
		case ProcedureCode_UEContextSetup:
			return new(UEContextSetupRequest)
		case ProcedureCode_UEContextRelease:
			return new(UEContextReleaseCommand)
		case ProcedureCode_UEContextModification:
			return new(UEContextModificationRequest)
		case ProcedureCode_UEContextModificationRequired:
			return new(UEContextModificationRequired)
		case ProcedureCode_UEContextReleaseRequest:
			return new(UEContextReleaseRequest)
		case ProcedureCode_InitialULRRCMessageTransfer:
			return new(InitialULRRCMessageTransfer)
		case ProcedureCode_DLRRCMessageTransfer:
			return new(DLRRCMessageTransfer)
		case ProcedureCode_ULRRCMessageTransfer:
			return new(ULRRCMessageTransfer)
		case ProcedureCode_UEInactivityNotification:
			return new(UEInactivityNotification)
		case ProcedureCode_GNBDUResourceCoordination:
			return new(GNBDUResourceCoordinationRequest)
		case ProcedureCode_SystemInformationDeliveryCommand:
			return new(SystemInformationDeliveryCommand)
		case ProcedureCode_Paging:
			return new(Paging)
		case ProcedureCode_Notify:
			return new(Notify)
		case ProcedureCode_WriteReplaceWarning:
			return new(WriteReplaceWarningRequest)
		case ProcedureCode_PWSCancel:
			return new(PWSCancelRequest)
		case ProcedureCode_PWSRestartIndication:
			return new(PWSRestartIndication)
		case ProcedureCode_PWSFailureIndication:
			return new(PWSFailureIndication)
		case ProcedureCode_GNBDUStatusIndication:
			return new(GNBDUStatusIndication)
		case ProcedureCode_RRCDeliveryReport:
			return new(RRCDeliveryReport)
		case ProcedureCode_F1Removal:
			return new(F1RemovalRequest)
		case ProcedureCode_NetworkAccessRateReduction:
			return new(NetworkAccessRateReduction)
		case ProcedureCode_TraceStart:
			return new(TraceStart)
		case ProcedureCode_DeactivateTrace:
			return new(DeactivateTrace)
		case ProcedureCode_DUCURadioInformationTransfer:
			return new(DUCURadioInformationTransfer)
		case ProcedureCode_CUDURadioInformationTransfer:
			return new(CUDURadioInformationTransfer)
		case ProcedureCode_BAPMappingConfiguration:
			return new(BAPMappingConfiguration)
		case ProcedureCode_GNBDUResourceConfiguration:
			return new(GNBDUResourceConfiguration)
		case ProcedureCode_IABTNLAddressAllocation:
			return new(IABTNLAddressRequest)
		case ProcedureCode_IABUPConfigurationUpdate:
			return new(IABUPConfigurationUpdateRequest)
		case ProcedureCode_ResourceStatusReportingInitiation:
			return new(ResourceStatusRequest)
		case ProcedureCode_ResourceStatusReporting:
			return new(ResourceStatusUpdate)
		case ProcedureCode_AccessAndMobilityIndication:
			return new(AccessAndMobilityIndication)
		case ProcedureCode_AccessSuccess:
			return new(AccessSuccess)
		case ProcedureCode_CellTrafficTrace:
			return new(CellTrafficTrace)
		case ProcedureCode_PositioningMeasurementExchange:
			return new(PositioningMeasurementRequest)
		case ProcedureCode_PositioningAssistanceInformationControl:
			return new(PositioningAssistanceInformationControl)
		case ProcedureCode_PositioningAssistanceInformationFeedback:
			return new(PositioningAssistanceInformationFeedback)
		case ProcedureCode_PositioningMeasurementReport:
			return new(PositioningMeasurementReport)
		case ProcedureCode_PositioningMeasurementAbort:
			return new(PositioningMeasurementAbort)
		case ProcedureCode_PositioningMeasurementFailureIndication:
			return new(PositioningMeasurementFailureIndication)
		case ProcedureCode_PositioningMeasurementUpdate:
			return new(PositioningMeasurementUpdate)
		case ProcedureCode_TRPInformationExchange:
			return new(TRPInformationRequest)
		case ProcedureCode_PositioningInformationExchange:
			return new(PositioningInformationRequest)
		case ProcedureCode_PositioningActivation:
			return new(PositioningActivationRequest)
		case ProcedureCode_PositioningDeactivation:
			return new(PositioningDeactivation)
		case ProcedureCode_ECIDMeasurementInitiation:
			return new(ECIDMeasurementInitiationRequest)
		case ProcedureCode_ECIDMeasurementFailureIndication:
			return new(ECIDMeasurementFailureIndication)
		case ProcedureCode_ECIDMeasurementReport:
			return new(ECIDMeasurementReport)
		case ProcedureCode_ECIDMeasurementTermination:
			return new(ECIDMeasurementTerminationCommand)
		case ProcedureCode_PositioningInformationUpdate:
			return new(PositioningInformationUpdate)
		case ProcedureCode_ReferenceTimeInformationReport:
			return new(ReferenceTimeInformationReport)
		case ProcedureCode_ReferenceTimeInformationReportingControl:
			return new(ReferenceTimeInformationReportingControl)
		}
		
	case F1apPduSuccessfulOutcome:
		switch int64(procedureCode.Value) {
		case ProcedureCode_Reset:
			return new(ResetAcknowledge)
		case ProcedureCode_F1Setup:
			return new(F1SetupResponse)
		case ProcedureCode_GNBDUConfigurationUpdate:
			return new(GNBDUConfigurationUpdateAcknowledge)
		case ProcedureCode_GNBCUConfigurationUpdate:
			return new(GNBCUConfigurationUpdateAcknowledge)
		case ProcedureCode_UEContextSetup:
			return new(UEContextSetupResponse)
		case ProcedureCode_UEContextRelease:
			return new(UEContextReleaseComplete)
		case ProcedureCode_UEContextModification:
			return new(UEContextModificationResponse)
		case ProcedureCode_UEContextModificationRequired:
			return new(UEContextModificationConfirm)
		case ProcedureCode_WriteReplaceWarning:
			return new(WriteReplaceWarningResponse)
		case ProcedureCode_PWSCancel:
			return new(PWSCancelResponse)
		case ProcedureCode_GNBDUResourceCoordination:
			return new(GNBDUResourceCoordinationResponse)
		case ProcedureCode_F1Removal:
			return new(F1RemovalResponse)
		case ProcedureCode_BAPMappingConfiguration:
			return new(BAPMappingConfigurationAcknowledge)
		case ProcedureCode_GNBDUResourceConfiguration:
			return new(GNBDUResourceConfigurationAcknowledge)
		case ProcedureCode_IABTNLAddressAllocation:
			return new(IABTNLAddressResponse)
		case ProcedureCode_IABUPConfigurationUpdate:
			return new(IABUPConfigurationUpdateResponse)
		case ProcedureCode_ResourceStatusReportingInitiation:
			return new(ResourceStatusResponse)
		case ProcedureCode_PositioningMeasurementExchange:
			return new(PositioningMeasurementResponse)
		case ProcedureCode_TRPInformationExchange:
			return new(TRPInformationResponse)
		case ProcedureCode_PositioningInformationExchange:
			return new(PositioningInformationResponse)
		case ProcedureCode_PositioningActivation:
			return new(PositioningActivationResponse)
		case ProcedureCode_ECIDMeasurementInitiation:
			return new(ECIDMeasurementInitiationResponse)
		}
		
	case F1apPduUnsuccessfulOutcome:
		switch int64(procedureCode.Value) {
		case ProcedureCode_F1Setup:
			return new(F1SetupFailure)
		case ProcedureCode_GNBDUConfigurationUpdate:
			return new(GNBDUConfigurationUpdateFailure)
		case ProcedureCode_GNBCUConfigurationUpdate:
			return new(GNBCUConfigurationUpdateFailure)
		case ProcedureCode_UEContextSetup:
			return new(UEContextSetupFailure)
		case ProcedureCode_UEContextModification:
			return new(UEContextModificationFailure)
		case ProcedureCode_UEContextModificationRequired:
			return new(UEContextModificationRefuse)
		case ProcedureCode_IABUPConfigurationUpdate:
			return new(IABUPConfigurationUpdateFailure)
		case ProcedureCode_ResourceStatusReportingInitiation:
			return new(ResourceStatusFailure)
		case ProcedureCode_PositioningMeasurementExchange:
			return new(PositioningMeasurementFailure)
		case ProcedureCode_TRPInformationExchange:
			return new(TRPInformationFailure)
		case ProcedureCode_PositioningInformationExchange:
			return new(PositioningInformationFailure)
		case ProcedureCode_PositioningActivation:
			return new(PositioningActivationFailure)
		case ProcedureCode_ECIDMeasurementInitiation:
			return new(ECIDMeasurementInitiationFailure)
		}
		
	default:
		return nil
	}
	return nil
}